# Generated by Django 5.2.4 on 2025-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='previous',
            field=models.TextField(max_length=2000),
        ),
    ]
