# Generated by Django 5.2.4 on 2025-07-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_resume_previous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='previous',
            new_name='pervious',
        ),
    ]
